theme: jekyll-theme-slate
# title: Homepage
# description: Bookmark
# render_with_liquid: false  # Более явное отключение
# markdown: CommonMark
plugins:
  - jekyll-relative-links
minimal:
  skin: dark